import * as THREE from 'https://unpkg.com/three@0.166.1/build/three.module.js';

const $=id=>document.getElementById(id);
const ui={start:$('startBtn'),pause:$('pauseBtn'),reset:$('resetBtn'),again:$('againBtn'),speed:$('speedRange'),speedLabel:$('speedLabel'),redBar:$('redBleedBar'),blueBar:$('blueBleedBar'),redText:$('redBleedText'),blueText:$('blueBleedText'),redStatus:$('redStatus'),blueStatus:$('blueStatus'),limit:$('bleedLimit'),limitVal:$('bleedLimitValue'),limitTop:$('bleedLimitText'),detach:$('detachChance'),detachVal:$('detachChanceValue'),agg:$('aggression'),aggVal:$('aggressionValue'),state:$('matchState'),time:$('timeLabel'),overlay:$('winnerOverlay'),winner:$('winnerText'),log:$('combatLog'),clear:$('clearLogBtn'),live:document.querySelector('.live-pill')};
const LABEL={head:'머리',torso:'몸통',leftArm:'왼팔',rightArm:'오른팔',leftLeg:'왼다리',rightLeg:'오른다리'};
const LIMBS=['leftArm','rightArm','leftLeg','rightLeg'];
const TARGETS=['torso','leftArm','rightArm','leftLeg','rightLeg','head'];
const cfg=()=>({limit:+ui.limit.value,detach:+ui.detach.value/100,agg:+ui.agg.value/100});
const parts=()=>({head:{hp:70,max:70,attached:true},torso:{hp:150,max:150,attached:true},leftArm:{hp:70,max:70,attached:true},rightArm:{hp:70,max:70,attached:true},leftLeg:{hp:85,max:85,attached:true},rightLeg:{hp:85,max:85,attached:true}});

const viewport=$('viewport3d'),scene=new THREE.Scene();
scene.background=new THREE.Color(0x091018); scene.fog=new THREE.Fog(0x091018,16,34);
const camera=new THREE.PerspectiveCamera(47,16/9,.1,80); camera.position.set(0,4.8,13.2);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; viewport.appendChild(renderer.domElement);
const clock=new THREE.Clock(), tmp=new THREE.Vector3();
const S={running:false,finished:false,time:0,speed:1,red:null,blue:null,debris:[],weapons:[],sparks:[]};

function mat(c,metal=.25,rough=.45){return new THREE.MeshStandardMaterial({color:c,metalness:metal,roughness:rough});}
function mesh(g,m){const x=new THREE.Mesh(g,m);x.castShadow=true;x.receiveShadow=true;return x;}
function limb(radius,len,m){const g=new THREE.Group();const b=mesh(new THREE.CylinderGeometry(radius,radius,len,14),m);g.add(b);const a=mesh(new THREE.SphereGeometry(radius,14,12),m);a.position.y=len/2;g.add(a);const c=a.clone();c.position.y=-len/2;g.add(c);return g;}
function joint(r=.12){return mesh(new THREE.SphereGeometry(r,14,12),mat(0x080d14,.5,.3));}
function weapon(type){const g=new THREE.Group();if(type==='spear'){const shaft=mesh(new THREE.CylinderGeometry(.045,.045,2.7,10),mat(0x8b6846,.1,.8));shaft.rotation.z=Math.PI/2;g.add(shaft);const tip=mesh(new THREE.ConeGeometry(.11,.42,12),mat(0xe8eef7,.9,.18));tip.rotation.z=-Math.PI/2;tip.position.x=1.52;g.add(tip);}else{const h=mesh(new THREE.CylinderGeometry(.065,.065,.42,10),mat(0x3a291f,.1,.8));h.rotation.z=Math.PI/2;h.position.x=-.18;g.add(h);const b=mesh(new THREE.BoxGeometry(1.05,.08,.035),mat(0xe8eef7,.92,.16));b.position.x=.55;g.add(b);const guard=mesh(new THREE.BoxGeometry(.05,.23,.08),mat(0xaeb9c7,.7,.25));g.add(guard);}return g;}

function environment(){scene.add(new THREE.HemisphereLight(0xcfe2ff,0x151a22,1.45));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(5,12,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-10;sun.shadow.camera.right=10;sun.shadow.camera.top=10;sun.shadow.camera.bottom=-10;scene.add(sun);const r=new THREE.PointLight(0xff3344,18,26,2);r.position.set(-6,5,4);scene.add(r);const b=new THREE.PointLight(0x3377ff,18,26,2);b.position.set(6,5,4);scene.add(b);const floor=mesh(new THREE.CylinderGeometry(8.3,8.7,.5,64),mat(0x151c26,.2,.82));floor.position.y=-.27;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(16,20,0x2a3546,0x1f2835);grid.position.y=.02;grid.material.transparent=true;grid.material.opacity=.35;scene.add(grid);const ring=mesh(new THREE.TorusGeometry(8,.08,12,96),mat(0x3b4656,.7,.25));ring.rotation.x=Math.PI/2;ring.position.y=.04;scene.add(ring);}

function addArm(f,side){const s=side==='left'?-1:1,p=new THREE.Group();p.position.set(.58*s,.67,0);f.torsoPivot.add(p);f.pivots[side+'Arm']=p;const up=limb(.13,.62,f.bodyMat);up.position.y=-.31;p.add(up);const elbow=new THREE.Group();elbow.position.y=-.63;p.add(elbow);elbow.add(joint(.11));const low=limb(.105,.56,f.bodyMat);low.position.y=-.3;elbow.add(low);const hand=new THREE.Group();hand.position.y=-.61;elbow.add(hand);f.refs[side+'Hand']=hand;}
function addLeg(f,side){const s=side==='left'?-1:1,p=new THREE.Group();p.position.set(.24*s,-1.03,0);f.torsoPivot.add(p);f.pivots[side+'Leg']=p;const up=limb(.16,.78,f.bodyMat);up.position.y=-.39;p.add(up);const knee=new THREE.Group();knee.position.y=-.8;p.add(knee);knee.add(joint(.13));const low=limb(.135,.76,f.bodyMat);low.position.y=-.39;knee.add(low);const foot=mesh(new THREE.BoxGeometry(.28,.13,.48),f.bodyMat);foot.position.set(0,-.81,.13);knee.add(foot);}
function fighter(team,x,facing,type){const color=team==='red'?0xff3b47:0x3d7cff;const f={team,color,x,z:team==='red'?-.65:.65,facing,weapon:type,weaponHeld:true,bleed:0,bleedRate:0,parts:parts(),vx:0,cool:.5+Math.random()*.3,atk:0,atkDur:.4,atkKind:null,target:null,hit:false,stagger:0,seed:Math.random()*1000,group:new THREE.Group(),pivots:{},refs:{},bodyMat:mat(color,.28,.42)};f.group.position.set(x,0,f.z);scene.add(f.group);const sh=new THREE.Mesh(new THREE.CircleGeometry(.68,28),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.3}));sh.rotation.x=-Math.PI/2;sh.position.y=.03;f.group.add(sh);f.shadow=sh;const tp=new THREE.Group();tp.position.y=2.55;f.group.add(tp);f.torsoPivot=tp;f.pivots.torso=tp;const torso=mesh(new THREE.CylinderGeometry(.43,.5,1.35,18),f.bodyMat);tp.add(torso);const shoulder=mesh(new THREE.SphereGeometry(.5,18,14),f.bodyMat);shoulder.scale.y=.6;shoulder.position.y=.62;tp.add(shoulder);const hip=mesh(new THREE.SphereGeometry(.42,18,14),f.bodyMat);hip.scale.y=.58;hip.position.y=-.64;tp.add(hip);const hp=new THREE.Group();hp.position.y=1.08;tp.add(hp);f.pivots.head=hp;const neck=mesh(new THREE.CylinderGeometry(.11,.11,.24,12),f.bodyMat);neck.position.y=-.15;hp.add(neck);const head=mesh(new THREE.SphereGeometry(.39,20,16),f.bodyMat);head.position.y=.27;hp.add(head);const eye=mesh(new THREE.SphereGeometry(.035,10,8),mat(0xf4f9ff,0,.2));eye.position.set(.14,.29,.34);hp.add(eye);addArm(f,'left');addArm(f,'right');addLeg(f,'left');addLeg(f,'right');const w=weapon(type);if(type==='spear'){w.rotation.y=Math.PI/2;w.position.set(.83,-.05,0);}else w.position.set(.45,0,0);f.refs.rightHand.add(w);f.weaponObj=w;return f;}

function mobility(f){const n=+f.parts.leftLeg.attached + +f.parts.rightLeg.attached;if(n===2)return 1;if(n===1)return .54;return (f.parts.leftArm.attached||f.parts.rightArm.attached)?.15:0;}
function profile(f){if(f.weaponHeld&&f.parts.rightArm.attached)return f.weapon==='spear'?{kind:'spear',reach:3.4,min:12,max:23,dur:.5,label:'창 찌르기'}:{kind:'knife',reach:1.95,min:15,max:28,dur:.4,label:'검 베기'};if(f.parts.leftArm.attached||f.parts.rightArm.attached)return{kind:'punch',reach:1.25,min:6,max:11,dur:.34,label:'남은 팔 공격'};if(f.parts.leftLeg.attached||f.parts.rightLeg.attached)return{kind:'kick',reach:1.5,min:8,max:13,dur:.42,label:'다리 공격'};return null;}
function pick(enemy,a){const arr=TARGETS.filter(k=>enemy.parts[k].attached);if(!arr.length)return'torso';const r=Math.random();if(a.weaponHeld&&a.weapon==='spear'&&r<.48)return'torso';if(a.weaponHeld&&a.weapon==='knife'&&r<.6){const l=LIMBS.filter(k=>enemy.parts[k].attached);if(l.length)return l[Math.floor(Math.random()*l.length)];}return arr[Math.floor(Math.random()*arr.length)];}
function begin(a,e,p){a.atkKind=p.kind;a.atkDur=p.dur;a.atk=p.dur;a.hit=false;a.target=pick(e,a);a.cool=.48+Math.random()*.45+(1-cfg().agg)*.65;}
function ai(f,e,dt){f.cool=Math.max(0,f.cool-dt);f.stagger=Math.max(0,f.stagger-dt);if(f.atk>0){f.atk-=dt;const q=1-f.atk/f.atkDur;if(!f.hit&&q>.53){f.hit=true;resolveHit(f,e);}return;}const p=profile(f);if(!p){f.vx*=Math.pow(.01,dt);return;}const d=Math.abs(e.x-f.x),m=mobility(f),a=cfg().agg;if(d>p.reach*.91){const v=(e.x>f.x?1:-1)*(2.25+1.7*a)*m;f.vx+=(v-f.vx)*Math.min(1,dt*5.5);}else if(d<Math.max(.78,p.reach*.42)){const v=(e.x>f.x?-1:1)*1.4*m;f.vx+=(v-f.vx)*Math.min(1,dt*5);}else{f.vx*=Math.pow(.08,dt);if(f.cool<=0&&Math.random()<dt*(2.3+a*3.1))begin(f,e,p);}if(f.stagger>0)f.vx*=.35;f.x=THREE.MathUtils.clamp(f.x+f.vx*dt,-5.8,5.8);f.facing=e.x>f.x?1:-1;}
function point(f,name){(f.pivots[name]||f.torsoPivot).getWorldPosition(tmp);return tmp.clone();}
function spark(pos,c,n=8){for(let i=0;i<n;i++){const m=mesh(new THREE.SphereGeometry(.035+Math.random()*.03,8,6),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.9}));m.position.copy(pos);scene.add(m);S.sparks.push({mesh:m,vx:(Math.random()-.5)*3,vy:(Math.random()-.1)*2.8,vz:(Math.random()-.5)*2,life:.35+Math.random()*.22,max:.55});}}
function resolveHit(a,d){const p=profile(a);if(!p)return;if(Math.abs(d.x-a.x)>p.reach+.4){log(a.team,p.label+' 빗나감');return;}if(Math.random()>.74+cfg().agg*.13){log(a.team,p.label+' 회피됨');return;}const name=d.parts[a.target]?.attached?a.target:'torso',part=d.parts[name],damage=p.min+Math.random()*(p.max-p.min),wf=p.kind==='knife'?1.15:p.kind==='spear'?.92:.4;part.hp=Math.max(0,part.hp-damage);d.bleed+=damage*.11*wf;d.bleedRate+=damage*.0025*wf;d.stagger=.12+damage*.007;d.vx+=a.facing*damage*.045;spark(point(d,name),a.color);log(a.team,p.label+' → '+LABEL[name]+' ('+Math.round(damage)+' 손상)');if(LIMBS.includes(name)&&part.hp<=0&&part.attached){const chance=cfg().detach*(p.kind==='knife'?1.15:p.kind==='spear'?.78:.16);if(Math.random()<chance)detachPart(d,name,a.facing);else{part.hp=3;d.bleedRate+=.035;}}finishCheck();}
function debrisMesh(f,name){const g=new THREE.Group(),m=mat(f.color,.25,.45),leg=name.includes('Leg');const a=limb(leg?.16:.13,leg?.68:.52,m);a.position.y=leg?.31:.25;const b=limb(leg?.135:.105,leg?.65:.5,m);b.position.y=leg?-.43:-.32;g.add(a,b);return g;}
function detachPart(f,name,dir){const part=f.parts[name];if(!part.attached)return;const pos=point(f,name);part.attached=false;part.hp=0;f.pivots[name].visible=false;const m=debrisMesh(f,name);m.position.copy(pos);scene.add(m);S.debris.push({mesh:m,vx:dir*(1.3+Math.random()),vy:2.2+Math.random(),vz:(Math.random()-.5),vr:(Math.random()-.5)*5,life:18});f.bleed+=5.5;f.bleedRate+=name.includes('Leg')?.22:.17;spark(pos,f.color,11);log(f.team,LABEL[name]+' 파츠 분리');if(name==='rightArm'&&f.weaponHeld){f.weaponHeld=false;f.weaponObj.visible=false;const w=weapon(f.weapon);w.position.copy(pos);scene.add(w);S.weapons.push({mesh:w,vx:dir*(1+Math.random()),vy:1.5+Math.random()*.7,vz:(Math.random()-.5)*.8,vr:(Math.random()-.5)*5});log(f.team,'오른팔 분리 → 무기 드롭, 무기 공격 불가');}}
function bleed(f,dt){const ex=(1-f.parts.torso.hp/f.parts.torso.max)*.018+(1-f.parts.head.hp/f.parts.head.max)*.009;f.bleed+=(f.bleedRate+ex)*dt*8;f.bleedRate*=Math.pow(.996,dt*60);}
function finishCheck(){const l=cfg().limit;if(S.red.bleed>=l||S.blue.bleed>=l)finish(S.red.bleed>=l?S.blue:S.red);}
function finish(w){if(S.finished)return;S.finished=true;S.running=false;ui.state.textContent='COMPLETE';ui.live.classList.remove('running');ui.winner.textContent=w.team.toUpperCase()+' WINS';ui.winner.style.color='#'+w.color.toString(16).padStart(6,'0');ui.overlay.classList.remove('hidden');log('SYSTEM',w.team.toUpperCase()+' 승리. 상대가 출혈 한계에 먼저 도달함.');}

function animate(f,dt){const t=S.time,m=Math.min(1,Math.abs(f.vx)/3),walk=Math.sin(t*7+f.seed)*m,q=f.atk>0?1-f.atk/f.atkDur:0,s=Math.sin(Math.min(1,q)*Math.PI);f.group.position.set(f.x,0,f.z);const target=f.facing>0?0:Math.PI;let diff=((target-f.group.rotation.y+Math.PI)%(Math.PI*2))-Math.PI;f.group.rotation.y+=diff*Math.min(1,dt*9);f.torsoPivot.position.y=2.55+Math.abs(Math.sin(t*7+f.seed))*.1*m;f.torsoPivot.rotation.z=THREE.MathUtils.lerp(f.torsoPivot.rotation.z,f.stagger>0?-.08*f.facing:f.vx*.025,Math.min(1,dt*7));f.pivots.head.rotation.z=Math.sin(t*2.3+f.seed)*.025+(f.stagger>0?-.09:0);if(f.parts.leftLeg.attached)f.pivots.leftLeg.rotation.x=.2*walk+(f.atkKind==='kick'&&f.atk>0?.9*s:0);if(f.parts.rightLeg.attached)f.pivots.rightLeg.rotation.x=-.2*walk+(f.atkKind==='kick'&&f.atk>0?.5*s:0);if(f.parts.leftArm.attached){f.pivots.leftArm.rotation.x=-.18-.23*walk;f.pivots.leftArm.rotation.z=.08;if(!f.weaponHeld&&f.atkKind==='punch'&&f.atk>0){f.pivots.leftArm.rotation.x=-1.15*s;f.pivots.leftArm.rotation.z=-.12;}}if(f.parts.rightArm.attached){let x=-.18+.23*walk,z=-.08,y=0;if(f.weaponHeld&&f.atk>0){if(f.weapon==='spear'){x=-1.2*s;z=-.2;y=.12*s;}else{x=-.5-1.5*s;z=.55-1.1*s;y=-.22*s;}}else if(!f.weaponHeld&&f.atkKind==='punch'&&f.atk>0){x=-1.1*s;z=-.12;}f.pivots.rightArm.rotation.set(x,y,z);}f.shadow.scale.setScalar(1+m*.08);}
function physics(dt){for(const d of S.debris){d.vy-=5.8*dt;d.mesh.position.x+=d.vx*dt;d.mesh.position.y+=d.vy*dt;d.mesh.position.z+=d.vz*dt;d.mesh.rotation.x+=d.vr*dt;d.mesh.rotation.z+=d.vr*.7*dt;if(d.mesh.position.y<.18){d.mesh.position.y=.18;d.vy*=-.2;d.vx*=.8;d.vz*=.8;}d.life-=dt;}S.debris=S.debris.filter(d=>{if(d.life>0)return true;scene.remove(d.mesh);return false;});for(const w of S.weapons){w.vy-=5.8*dt;w.mesh.position.x+=w.vx*dt;w.mesh.position.y+=w.vy*dt;w.mesh.position.z+=w.vz*dt;w.mesh.rotation.z+=w.vr*dt;if(w.mesh.position.y<.1){w.mesh.position.y=.1;w.vy*=-.18;w.vx*=.78;w.vz*=.78;w.vr*=.8;}}for(const p of S.sparks){p.vy-=4.5*dt;p.mesh.position.x+=p.vx*dt;p.mesh.position.y+=p.vy*dt;p.mesh.position.z+=p.vz*dt;p.life-=dt;p.mesh.material.opacity=Math.max(0,p.life/p.max);}S.sparks=S.sparks.filter(p=>{if(p.life>0)return true;scene.remove(p.mesh);return false;});}
function status(f,root){root.innerHTML=['head','torso','leftArm','rightArm','leftLeg','rightLeg'].map(n=>{const p=f.parts[n],pct=Math.max(0,p.hp/p.max),cl=!p.attached?'off':pct<.36?'warn':'';return '<div class="limb-chip '+cl+'"><span>'+LABEL[n]+'</span><b>'+(p.attached?Math.round(pct*100)+'%':'분리')+'</b></div>'}).join('');}
function updateUI(){const l=cfg().limit,r=Math.min(l,S.red.bleed),b=Math.min(l,S.blue.bleed);ui.redBar.style.width=r/l*100+'%';ui.blueBar.style.width=b/l*100+'%';ui.redText.textContent=r.toFixed(1)+' / '+l;ui.blueText.textContent=b.toFixed(1)+' / '+l;ui.time.textContent=S.time.toFixed(1).padStart(4,'0')+'s';status(S.red,ui.redStatus);status(S.blue,ui.blueStatus);}
function log(team,msg){const row=document.createElement('div'),cl=team==='red'||team==='blue'?team:'';row.className='log-line';row.innerHTML='<span class="log-time">'+S.time.toFixed(1).padStart(4,'0')+'s</span><span class="log-team '+cl+'">'+team.toUpperCase()+'</span><span class="log-message">'+msg+'</span>';ui.log.prepend(row);while(ui.log.children.length>70)ui.log.lastChild.remove();}
function cleanup(){for(const x of [...S.debris,...S.weapons,...S.sparks])scene.remove(x.mesh);S.debris=[];S.weapons=[];S.sparks=[];if(S.red)scene.remove(S.red.group);if(S.blue)scene.remove(S.blue.group);}
function reset(){cleanup();S.running=false;S.finished=false;S.time=0;S.red=fighter('red',-3.2,1,'knife');S.blue=fighter('blue',3.2,-1,'spear');ui.overlay.classList.add('hidden');ui.state.textContent='READY';ui.live.classList.remove('running');ui.log.innerHTML='';log('SYSTEM','3D 시뮬레이션 초기화. 빨강: 검 / 파랑: 창');updateUI();}
function start(){if(S.finished)reset();S.running=true;ui.state.textContent='RUNNING';ui.live.classList.add('running');}
function pause(){if(S.finished)return;S.running=!S.running;ui.state.textContent=S.running?'RUNNING':'PAUSED';ui.live.classList.toggle('running',S.running);}
function resize(){const r=viewport.getBoundingClientRect();camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);}
function tick(){const raw=Math.min(.033,clock.getDelta()||0),dt=raw*S.speed;if(S.running&&!S.finished){S.time+=dt;ai(S.red,S.blue,dt);ai(S.blue,S.red,dt);bleed(S.red,dt);bleed(S.blue,dt);finishCheck();updateUI();}animate(S.red,dt);animate(S.blue,dt);physics(dt);camera.position.x+=(((S.red.x+S.blue.x)*.1)-camera.position.x)*Math.min(1,raw*2.5);camera.lookAt((S.red.x+S.blue.x)*.07,2.6,0);renderer.render(scene,camera);requestAnimationFrame(tick);}

ui.start.onclick=start;ui.pause.onclick=pause;ui.reset.onclick=reset;ui.again.onclick=()=>{reset();start();};ui.clear.onclick=()=>ui.log.innerHTML='';ui.speed.oninput=()=>{S.speed=+ui.speed.value;ui.speedLabel.textContent=S.speed.toFixed(2)+'×';};ui.limit.oninput=()=>{ui.limitVal.textContent=ui.limit.value;ui.limitTop.textContent=ui.limit.value;updateUI();};ui.detach.oninput=()=>ui.detachVal.textContent=ui.detach.value+'%';ui.agg.oninput=()=>ui.aggVal.textContent=ui.agg.value+'%';addEventListener('resize',resize);
environment();resize();reset();requestAnimationFrame(tick);